# @format

version: "3"
networks:
  harvest-web_harvest_network:
    external: true
volumes:
  caddy_data:
  caddy_config:
  db_data:

services:
  mariadb:
    image: mariadb:10.11.2
    restart: always
    networks:
      - harvest-web_harvest_network
    ports:
      - 3307:3306
    environment:
      MARIADB_USER: harvestj
      MARIADB_PASSWORD: harvestj
      MARIADB_ROOT_PASSWORD: harvestj
  wordpress:
    image: wordpress:${WP_VERSION:-latest}
    restart: always
    ports:
      - ${WP_PORT:-8080}:80
    depends_on:
      - mariadb
    networks:
      - harvest-web_harvest_network

    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./public:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: harvestj
      WORDPRESS_DB_PASSWORD: harvestj
      WORDPRESS_DB_NAME: harvestj
  caddy:
    image: caddy:2.7.6-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - harvest-web_harvest_network
