name: Export WordPress files and database from server
on:
  workflow_call:
    inputs:
      SSH_HOST:
        required: true
        type: string
      SSH_PORT:
        required: true
        type: string
      ENV:
        required: true
        type: string
      DB_HOST:
        required: true
        type: string
        default: localhost

jobs:
  export:
    runs-on: ubuntu-20.04
    env:
      DB_PASSWORD: ${{ secrets[format('DB_PASSWORD_{0}', inputs.ENV)] }}
      DB_HOST: ${{ inputs.DB_HOST }}
      ssh_key: ${{ secrets[format('{0}_SSH_KEY', inputs.ENV)] }}
      WP_HOST: ${{ inputs.SSH_HOST }}
      SSH_PORT: ${{ inputs.SSH_PORT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.ssh_key }}
      - name: Execute export script
        run: scripts/export.sh
      - name: Add WP files
        run: |
          git config advice.addIgnoredFile false
          git add public/* || true
      - name: Commit and push
        run: |
          git config --global user.name 'Export WordPress from server'
          git config --global user.email 'dev.admin@harvest.au'
          git commit -am "Export WordPress from server"
          git push
